name: CI/CD Pipeline for Terraform with Rollback

on:
  push:
    branches:
      - main   # Executar na branch principal
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-west-2"  # Região AWS
  TF_VERSION: "1.5.0"      # Versão do Terraform
  WORKING_DIR: "./terraform"  # Diretório dos arquivos Terraform

jobs:
  terraform:
    name: "Terraform CI/CD"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configuração do Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 3. Configuração das credenciais AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Inicialização do Terraform
      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      # 5. Validação do código
      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      # 6. Geração do plano
      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -out=tfplan

      # 7. Aplicação do plano com rollback em caso de falha
      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform apply -auto-approve tfplan || (echo "Terraform Apply falhou! Iniciando rollback..." && terraform apply -auto-approve -var-file=rollback.tfvars)
        continue-on-error: false

      # 8. Notificação de sucesso
      - name: Notify Success
        if: success()
        run: echo "🚀 Terraform Apply concluído com sucesso!"

      # 9. Notificação de falha com rollback
      - name: Notify Failure
        if: failure()
        run: echo "⚠️ Terraform Apply falhou! Rollback executado com sucesso!"
