name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-west-2"
  EKS_CLUSTER: "online-boutique-eks"
  K8S_MANIFEST_PATH: "./kubernetes-manifests"

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar as credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Configurar o kubectl
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
          kubectl get nodes

      # Aplicar Manifests Kubernetes
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k ${{ env.K8S_MANIFEST_PATH }}

      # Verificar status dos pods
      - name: Check pod status
        run: |
          kubectl get pods -n default
